Adding ask_for_confirmation if copy fails
Also improving documentation a bit.

diff --git a/gash-rotate b/gash-rotate
--- a/gash-rotate
+++ b/gash-rotate
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
-# Create a timestamped copy of a file. Optionally
-# cleanup already exsiting copies.
+# Write timestamped copy of a file. And/or remove
+# already exsiting copies.
 
 #######################################
 # Write usage info to stderr and exit
@@ -64,7 +64,7 @@ readonly USAGE="$NAME [options] [command] FILE"
 readonly HINT="-h for help"
 
 readonly DESCRIPTION=$( cat << description
-Create a timestamped copy of a file. And/or cleanup
+Write timestamped copy of a file. And/or remove
 already existing copies.
 description
 )
@@ -73,12 +73,12 @@ readonly ARGUMENTS=$( cat << arguments
 \tCOMMAND ............... Command to be executed.
 \t                          copy|co :: Write timestamped
 \t                            copy of FILE.
-\t                          clean|cl :: Remove oldest timestapmed
+\t                          clean|cl :: Remove old timestamped
 \t                            copies of FILE.
 \t                          copyclean|cc :: Copy, then clean
 \t                          list|ls :: List existing timestamped
 \t                            copies of FILE.
-\t                        (default: copy)
+\t                        (default: ´copy´)
 \tFILE .................. Path to file you want to rotate.
 arguments
 )
@@ -93,65 +93,51 @@ readonly OPTIONS=$( cat << options
 \t                        apply force to all cp and rm operations.
 \t-v (verbose) .......... More output.
 \t-d (dry-run) .......... Do not actually execute commands.
-\t-c (color) ............ Write status information without color.
+\t-c (color) ............ No color for output.
 \t-V (version) .......... Print version and exit.
 \t-h (help) ............. Print help and exit.
 options
 )
 
 readonly RETENTIONMODE=$(cat << retentionmode
-\tThe behaviour of the clean command is determined by the choosen
-\tretention mode. A mode is defined by four numbers, combined by
-\tdots:
+\tBehaviour of the clean command is determined by the choosen
+\tretention mode, defined by four numbers combined by dots:
 \t
 \tDAY.MONTH.YEAR.ALL
 \t
-\tDAY ...... In it's first step the clean command will check if
+\tDAY ...... In it's first step, the clean command will check if
 \t           the number of timestamped copies of FILE written
-\t           today exeeds the number given here. If so it will
+\t           today exeeds the number given here. If so, it will
 \t           delete the oldest copies until the number matches.
 \t           To skip this step choose ´0´.
-\tMONTH .... In it's second step the clean command will check if
+\tMONTH .... In it's second step, the clean command will check if
 \t           the number of timestamped copies (*including* those
 \t           written today) exeeds this number and delete the
 \t           the oldest ones if neccessary. To skip this step
 \t           choose ´0´.
-\tYEAR ..... In it's thitd step clean will count all timesptamped
+\tYEAR ..... In it's thitd step, clean will count all timesptamped
 \t           copies written this year (*inluding* this month and
-\t           today) exeeds this number and delete the oldest 
-\t           ones if neccessary. To skip this step choose ´0´.
-\tALL ...... In it's final step clean will count all excisting
+\t           today) and delete the oldest ones if neccessary. To 
+\t           skip this step choose ´0´.
+\tALL ...... In it's final step, clean will count all excisting
 \t           timestamped copies (regardless when they where
-\t           written) and delete the oldest ones if they exeed
+\t           written) and delete the oldest ones, if they exeed
 \t           this number. To skip this step choose ´0´.
 \t
 \tExamples:
 \t0.0.0.64 .... Just keep up to 64 copies, regardless when they
 \t              where written. This is the default.
 \t2.4.8.0 ..... If more than two copies with todays timestamp
-\t              exist: Delete the oldest ones until only two
-\t              remain.
+\t                exist: Delete the oldest ones until only two
+\t                remain.
 \t              If more than four copies with this months timestamp
-\t              exist (including the up to two from today):
-\t              Delete the oldest ones until only four remain.
+\t                exist (including the up to two from today):
+\t                Delete the oldest ones until only four remain.
 \t              If more than eight copies with this years timestamp
 \t              exist (including those from this month and today):
-\t              Delete the oldest ones until only four remain.
+\t                Delete the oldest ones until only eight remain.
 \t              Do not delete any copies from previous years.
 retentionmode
-)
-
-readonly ENVIROMENT_VARIABLES=$( cat << enviroment_variables
-\tGASHOPT_TIMESTAMP ..... true|false (default: false)
-\t                        Include iso 8601 timestamp in output. Can be
-\t                        overwritten by ´-t´ option.
-\tGASHOPT_COLOR ......... true|false (default: true)
-\t                        Write status information with color. Can be
-\t                        overwritten by ´-c´ option.
-\tGASHOPT_DRYRUN ........ true|false (default: false)
-\t                        Don't execute command. Can be overwritten by
-\t                        ´-d´ option.
-enviroment_variables
 )
 
 readonly HELP=$( cat << help
@@ -171,8 +157,6 @@ $OPTIONS
 Retention mode:
 $RETENTIONMODE
 
-Enviroment variables:
-$ENVIROMENT_VARIABLES
 help
 )
 
@@ -308,6 +292,10 @@ fi
 if $COPY; then
 	gash-echo "DEBUG" "======[ Copy ]======"
 	gash-exec "cp$F-v $FILEPATH $TARGET$(date +%Y%m%d%H%M%S).$FILEEXTENSION" "Writing timestamped copy of '$FILENAMEFULL'"
+	if [[ $? -ne 0 ]]; then
+		gash-echo "WARN" "Failed to write copy of '$FILENAMEFULL'"
+		ask_for_continue
+	fi
 fi
 
 ##
