Execution and output control

diff --git a/gash-run b/gash-run
--- a/gash-run
+++ b/gash-run
@@ -130,13 +130,39 @@ readonly MESSAGE="$2"
 ##
 ## Output
 ##
-gash-log -o "-en" "INFO" "$MESSAGE..."
+gash-log -o "-en" "INFO" "$MESSAGE... " 1>&2
 
-if [[ $GASHOPT_VERBOSE || $GASHOPT_DRYRUN ]]; then
-	echo -e "\n>> $COMMAND"
+if $GASHOPT_VERBOSE ; then
+	echo -e "\n>>> $COMMAND" 1>&2
+fi
+
+##
+## Execution
+##
+if $GASHOPT_DRYRUN; then
+	RESULT=0
+else
+	OUTPUT="$($COMMAND 2>&1)"
+	RESULT=$?
+fi
+
+##
+## Result
+##
+if $GASHOPT_VERBOSE; then
+	echo -e "$OUTPUT" 1>&2
+	echo -en "<<< " 1>&2
+fi
+
+if $GASHOPT_DRYRUN; then
+	echo -e "(Dry run)" 1>&2
+elif [[ $RESULT -eq 0 ]]; then
+	echo -e "(Ok)" 1>&2
+else
+	echo -e "(Failed)" 1>&2
 fi
 
 ##
 ## Done
 ##
-exit 0
+exit $RESULT
